"""Builds report/ReflexDebug_Lab_Report.pdf from the code, the real experiment outputs and a real demo run.

  python report/build_report.py

Inputs (generated by the project itself):
  results/mutation_study.json   python -m benchmark.mutation_study
  results/safety_eval.json      python -m benchmark.safety_eval
  results/benchmark.json        python cli.py bench   (optional; needs an OpenAI key)
The unit tests, the hidden-test reference check and the scripted demo are executed while building.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(HERE))

from reportlab.lib import colors  # noqa: E402
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY  # noqa: E402
from reportlab.lib.pagesizes import A4  # noqa: E402
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet  # noqa: E402
from reportlab.lib.units import cm  # noqa: E402
from reportlab.platypus import (  # noqa: E402
    Image, KeepTogether, ListFlowable, ListItem, PageBreak, Paragraph, Preformatted, SimpleDocTemplate, Spacer, Table,
    TableStyle,
)

import content as C  # noqa: E402
import figures as F  # noqa: E402
from benchmark.hidden_tests import HIDDEN  # noqa: E402
from benchmark.reference import REFERENCE  # noqa: E402
from benchmark.tasks import TASKS  # noqa: E402

RESULTS = ROOT / "results"
FIG = HERE / "figures"
OUT = HERE / "ReflexDebug_Lab_Report.pdf"

INK = colors.HexColor("#0b0b0b")
INK2 = colors.HexColor("#52514e")
ACCENT = colors.HexColor("#2a78d6")
RULE = colors.HexColor("#d9d8d3")
SHADE = colors.HexColor("#f4f4f1")

base = getSampleStyleSheet()
S = {
    "title": ParagraphStyle("title", parent=base["Title"], fontName="Helvetica-Bold", fontSize=22, leading=28,
                            textColor=INK, alignment=TA_CENTER, spaceAfter=10),
    "subtitle": ParagraphStyle("subtitle", parent=base["Normal"], fontName="Helvetica", fontSize=12.5, leading=17,
                               textColor=INK2, alignment=TA_CENTER),
    "h1": ParagraphStyle("h1", parent=base["Heading1"], fontName="Helvetica-Bold", fontSize=14.5, leading=19,
                         textColor=INK, spaceBefore=14, spaceAfter=6, keepWithNext=1),
    "h2": ParagraphStyle("h2", parent=base["Heading2"], fontName="Helvetica-Bold", fontSize=11.2, leading=15,
                         textColor=INK, spaceBefore=9, spaceAfter=4, keepWithNext=1),
    "body": ParagraphStyle("body", parent=base["BodyText"], fontName="Helvetica", fontSize=10, leading=14.2,
                           textColor=INK, alignment=TA_JUSTIFY, spaceAfter=6),
    "cell": ParagraphStyle("cell", parent=base["BodyText"], fontName="Helvetica", fontSize=8.6, leading=11,
                           textColor=INK),
    "cellb": ParagraphStyle("cellb", parent=base["BodyText"], fontName="Helvetica-Bold", fontSize=8.6, leading=11,
                            textColor=INK),
    "code": ParagraphStyle("code", parent=base["Code"], fontName="Courier", fontSize=7.8, leading=9.8,
                           textColor=INK, backColor=SHADE, borderPadding=6, leftIndent=4, rightIndent=4,
                           spaceBefore=4, spaceAfter=8),
    "caption": ParagraphStyle("caption", parent=base["Italic"], fontName="Helvetica-Oblique", fontSize=8.6,
                              leading=11, textColor=INK2, alignment=TA_CENTER, spaceAfter=10),
    "note": ParagraphStyle("note", parent=base["BodyText"], fontName="Helvetica-Oblique", fontSize=9, leading=12.5,
                           textColor=INK2, spaceAfter=6),
}


def esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def P(text: str, style: str = "body") -> Paragraph:
    return Paragraph(text, S[style])


def bullets(items: list[str]) -> ListFlowable:
    return ListFlowable([ListItem(P(i), leftIndent=14) for i in items], bulletType="bullet", start="\u2022",
                        leftIndent=14, bulletFontName="Helvetica", bulletFontSize=9)


def table(rows: list[list], widths: list[float], header: bool = True) -> Table:
    data = [[c if not isinstance(c, str) else Paragraph(esc(c), S["cellb" if header and i == 0 else "cell"])
             for c in row] for i, row in enumerate(rows)]
    t = Table(data, colWidths=[w * cm for w in widths], repeatRows=1 if header else 0)
    style = [
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, RULE),
        ("TOPPADDING", (0, 0), (-1, -1), 3.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
    ]
    if header:
        style += [("BACKGROUND", (0, 0), (-1, 0), SHADE), ("LINEBELOW", (0, 0), (-1, 0), 0.8, INK2)]
    t.setStyle(TableStyle(style))
    return t


def captioned(t: Table, caption: str) -> KeepTogether:
    return KeepTogether([t, P(caption, "caption")])


def figure(path: Path, width_cm: float, caption: str) -> KeepTogether:
    from reportlab.lib.utils import ImageReader

    iw, ih = ImageReader(str(path)).getSize()
    w = width_cm * cm
    return KeepTogether([Image(str(path), width=w, height=w * ih / iw), P(caption, "caption")])


def pct(x: float) -> str:
    return f"{x * 100:.1f}%"


# data collection

def run_unit_tests() -> tuple[int, int]:
    proc = subprocess.run([sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider"], cwd=ROOT,
                          capture_output=True, text=True)
    passed = int(m.group(1)) if (m := re.search(r"(\d+) passed", proc.stdout)) else 0
    failed = int(m.group(1)) if (m := re.search(r"(\d+) failed", proc.stdout)) else 0
    return passed, failed


def reference_check() -> list[tuple[str, int, int]]:
    from reflexdebug.config import Settings
    from reflexdebug.sandbox import Sandbox

    sb = Sandbox(Settings())
    out = []
    for t in TASKS:
        r = sb.run_tests(REFERENCE[t["id"]], HIDDEN[t["id"]])
        out.append((t["id"], len(r.passed), r.total))
    return out


def run_demo():
    from reflexdebug import ReflexDebugAgent, Settings
    from reflexdebug.demo import DEMO_TASK, demo_llm
    from reflexdebug.memory import ReflexionMemory

    settings = Settings()
    settings.max_steps_per_trial = 3
    llm = demo_llm()
    mem = ReflexionMemory(Path(tempfile.mkdtemp()) / "m.json", llm)
    return ReflexDebugAgent(llm, settings, memory=mem).solve(DEMO_TASK)


def assertion_locals_rate(records: list[dict]) -> float:
    firsts = [r["failures"][0] for r in records if r["detected"] and r["failures"]]
    a = [f for f in firsts if f["category"] == "assertion"]
    return sum(f["locals_captured"] for f in a) / (len(a) or 1)


# sections

def cover(story: list) -> None:
    story += [Spacer(1, 4.2 * cm), P(C.TITLE, "title"), Spacer(1, 0.3 * cm), P(C.SUBTITLE, "subtitle"),
              Spacer(1, 0.15 * cm), P(C.THEME, "subtitle"), Spacer(1, 2.6 * cm)]
    rows = [["Name", "Batch", "Roll number"]] + [list(a) for a in C.AUTHORS]
    t = table(rows, [6.5, 2.5, 4.5])
    t.hAlign = "CENTER"
    story += [t, PageBreak()]


def section_intro(story: list) -> None:
    story += [P("1. Aim", "h1"), P(C.AIM), P("2. Objectives", "h1"), bullets(C.OBJECTIVES), P("3. Theory", "h1")]
    for i, (head, text) in enumerate(C.THEORY, 1):
        story += [P(f"3.{i} {head}", "h2"), P(text)]
    story += [P("4. Problem statement and what is new", "h1"), P(C.PROBLEM),
              table([["Weakness of the basic loop", "ReflexDebug mechanism"]] + [list(r) for r in C.NOVELTY_ROWS],
                    [5.2, 11.3]),
              Spacer(1, 6)]


def section_design(story: list) -> None:
    story += [P("5. System architecture", "h1"),
              P("Figure 1 shows the complete pipeline. A task first becomes a validated specification. Lessons "
                "from earlier tasks are retrieved, and the coder writes a draft. Every draft and every edit passes "
                "the safety gate and runs in the sandbox, and the ReAct debugger works from the structured "
                "observations until the tests pass, the step budget runs out or the loop guard ends the trial. A "
                "failed trial produces a self-reflection that seeds the next one. At the end, a reusable lesson is "
                "distilled into long-term memory."),
              figure(FIG / "architecture.png", 16.2, "Figure 1. ReflexDebug architecture and control flow."),
              P("6. Algorithm", "h1"),
              Preformatted(C.PSEUDOCODE, S["code"]),
              P("The best draft is chosen by a simple score, pass rate plus one if every test passes, so a full "
                "pass always wins and a partially correct earlier draft is never lost when a later edit makes "
                "things worse. The same score decides which code is handed to the coder in the next trial."),
              P("7. Implementation", "h1"),
              P("The system is written in Python 3 and uses the OpenAI Chat Completions API with function calling "
                "(default model gpt-4o-mini) and text-embedding-3-small for memory. It has no framework "
                "dependencies: the ReAct loop, the tool dispatcher and the memory store are implemented directly, "
                "which keeps every step visible and easy to test. Table 2 lists the modules."),
              captioned(table([["Module", "Responsibility"]] + [list(m) for m in C.MODULES], [3.2, 13.3]),
                        "Table 2. Modules of the reflexdebug package."),
              P("7.1 Tools available to the agent", "h2"),
              captioned(table([["Tool", "What it does"]] + [list(t) for t in C.TOOLS], [3.2, 13.3]),
                        "Table 3. ReAct action space."),
              P("7.2 Specification synthesis and validation", "h2"),
              P("The spec prompt asks for 5 to 9 example tests that cover edge cases stated or implied by the task, "
                "and 2 to 4 Hypothesis property tests with small, bounded strategies. The response is JSON with the "
                "required signatures and the test module. Before it is accepted, the test module must pass the "
                "safety gate, import cleanly, and run against a stub whose functions raise NotImplementedError. "
                "Errors that have nothing to do with the solution (NameError, bad Hypothesis strategies, wrong call "
                "signatures) are sent back to the model for repair, up to two times. Tests that pass against the "
                "stub are recorded as vacuous, because they cannot detect any bug."),
              P("7.3 Interfaces", "h2"),
              P("cli.py renders the event stream in the terminal with coloured panels for thoughts, actions, "
                "observations, reflections and lessons, and prints a summary of steps, tool usage, tokens and cost. "
                "app.py is a Streamlit interface with a live trajectory, code diffs for each edit, a healing curve, "
                "tool usage, a memory browser and a benchmark dashboard. Both work in an offline demo mode that "
                "replays recorded model replies while executing every test for real.")]


def section_safety(story: list, safety: dict) -> None:
    s = safety["summary"]
    story += [P("8. Safety design", "h1"), P(C.SAFETY_TEXT),
              P(f"We evaluated both layers with benchmark/safety_eval.py. The gate blocked "
                f"{s['hostile_blocked']} of {s['hostile_samples']} hostile samples and accepted "
                f"{s['benign_accepted']} of {s['benign_samples']} benign programs (all reference solutions, all "
                f"hidden test modules and the demo files), so it produced no false positives on this corpus. "
                f"Table 4 shows how the process layer handled programs that the gate allows but that abuse "
                f"resources.")]
    rows = [["Program", "Reported as", "Time to contain"]]
    for name, v in safety["abuse"].items():
        rows.append([name, v["reported_as"], f"{v['seconds']:.2f} s"])
    story += [captioned(table(rows, [5.5, 5.5, 4]), "Table 4. Resource-abuse programs contained by the sandbox.")]


def section_setup(story: list) -> None:
    story += [P("9. Experimental setup", "h1"), P("9.1 Benchmark tasks", "h2"),
              P("We wrote 14 function-level tasks whose prompts are complete specifications but contain the kind "
                "of detail that single-shot generation tends to miss. Each task has a hidden test module that no "
                "agent ever sees, and a reference solution used only to prove that the hidden tests are correct."),
              captioned(table([["Task", "What makes it tricky"]] + [[t["title"], C.TASK_NOTES[t["id"]]] for t in TASKS],
                              [5.2, 11.3]), "Table 5. Benchmark tasks."),
              P("9.2 Ablation arms", "h2"),
              P("Four strategies share the same model and the same budget of LLM calls per task. They differ only "
                "in the mechanisms listed in Table 6, so any gap between neighbouring arms can be attributed to "
                "the mechanism that was added."),
              captioned(table([["Arm", "Spec", "Feedback", "Repair", "Reflexion + memory"]] + [list(a) for a in C.ARMS],
                    [3.1, 3.4, 4.3, 3.2, 2.5]), "Table 6. Ablation arms."),
              P("9.3 Metrics", "h2"),
              bullets([
                  "Solve rate: share of tasks whose final code passes every hidden test.",
                  "Hidden pass rate: share of hidden tests passed, averaged over tasks.",
                  "False confidence: the agent's own tests all pass but the hidden tests do not.",
                  "LLM calls, prompt and completion tokens, estimated cost in USD, and wall-clock time.",
                  "For the offline experiments: mutation score, failure categories and availability of each "
                  "feedback signal (Section 10.2), and block, accept and containment rates (Section 8).",
              ])]


def behaviour_section(bench: dict) -> list:
    rows = [r for r in bench["rows"] if r["strategy"] == "reflexdebug"]
    if not rows:
        return []
    tools: dict = {}
    trials = guards = disputes = reviews = triaged = errors = 0
    for r in rows:
        ex = r.get("extra") or {}
        for k, v in (ex.get("tool_counts") or {}).items():
            tools[k] = tools.get(k, 0) + v
        trials += ex.get("trials") or 0
        guards += ex.get("loop_guard_triggers") or 0
        disputes += len(ex.get("disputes") or [])
        reviews += len(ex.get("spec_review") or [])
        triaged += len(ex.get("spec_triage") or [])
        errors += bool(r.get("error")) and "budget" not in (r.get("error") or "")
    total_actions = sum(tools.values()) or 1
    evidence = sum(tools.get(k, 0) for k in ("trace_test", "eval_at_crash", "run_snippet", "inspect_failure"))
    edits = sum(tools.get(k, 0) for k in ("apply_patch", "rewrite_code"))
    tool_rows = [["Tool", "Calls", "Share"]] + [[k, str(v), f"{v / total_actions:.0%}"]
                                                for k, v in sorted(tools.items(), key=lambda kv: -kv[1])]
    text = (f"Across the {len(rows)} tasks the full agent ran {trials} Reflexion trials in total "
            f"({trials / len(rows):.1f} per task) and took {sum(tools.values())} ReAct actions: {evidence} evidence "
            f"actions (trace, eval, probe, inspect) and {edits} edits. The spec review changed {reviews} synthesised "
            f"tests before any code was written and evidence-based triage amended {triaged} more after the first "
            f"draft ran. The loop guard fired {guards} times, the agent itself disputed {disputes} tests, and "
            f"{errors} runs ended with an infrastructure error.")
    return [P("Agent behaviour", "h2"), P(text),
            captioned(table(tool_rows, [5, 3, 3]), "Table 11. ReAct actions taken by the full agent (all tasks).")]


def history_section(bench: dict, versions: list[tuple[str, dict]]) -> list:
    """ReflexDebug across development versions, plus the baselines of each run for context."""
    def agg(data, strat, tasks=None):
        rs = [r for r in data["rows"] if r["strategy"] == strat and (tasks is None or r["task"] in tasks)]
        if not rs:
            return None
        return (len(rs), sum(r["hidden_solved"] for r in rs), sum(r["hidden_pass_rate"] for r in rs) / len(rs),
                sum(r["usage"]["llm_calls"] for r in rs) / len(rs))

    rows = [["ReflexDebug version", "Tasks", "Solved", "Hidden pass", "LLM calls"]]
    for label, data in versions:
        a = agg(data, "reflexdebug")
        if a:
            rows.append([label, str(a[0]), f"{a[1]}/{a[0]}", pct(a[2]), f"{a[3]:.1f}"])
    return [P("10.6 How the agent changed across versions", "h2"),
            P("Table 12 shows the full agent in each development version: v1 (before the tracer, stopped after eight "
              "complete tasks), v2 (tracer and trace-driven fixes, before evidence-based spec triage) and the final "
              "version. The three baseline arms in Table 9 come from the v2 run and were not re-run, because none of "
              "the later changes touch them. Each version ran once, so differences of one task are within the "
              "run-to-run variation of the model."),
            captioned(table(rows, [5.4, 2.2, 2.4, 3, 2.6]), "Table 12. The full agent across development versions.")]


def audit_section(audit: dict | None, audit_v2: dict | None) -> list:
    if not audit:
        return []
    a = audit["summary"]
    out = [P("10.7 Auditing the synthesised specifications", "h2"),
           P("Because the reference solutions are known to be correct, each synthesised specification can itself be "
             "tested: a spec test that the reference solution fails is a wrong test. We also ran each run's first "
             "draft and final code against the hidden tests to see whether the repair loop helped "
             "(benchmark/spec_audit.py, no LLM calls).")]
    rows = [["Measure", "v2 (review only)" if audit_v2 else "", "Final (review + triage)"]]

    def line(label, key, fmt=str):
        v2 = fmt(audit_v2["summary"].get(key, 0)) if audit_v2 else ""
        rows.append([label, v2, fmt(a.get(key, 0))])

    line("Runs with a spec", "runs", lambda v: str(v))
    line("Specs the reference passes completely", "specs_consistent_with_reference")
    line("Wrong spec tests (reference fails them)", "spec_tests_wrong")
    line("Wrong spec tests before triage", "spec_tests_wrong_before_amendments")
    line("Tests amended by triage", "triage_amendments")
    line("... of which the test really was wrong", "triage_justified")
    line("First drafts that solve the task", "first_draft_solved")
    line("Final code that solves the task", "final_solved")
    line("Mean hidden pass: first draft", "mean_first_draft_hidden", pct)
    line("Mean hidden pass: final code", "mean_final_hidden", pct)
    line("Runs where repair improved hidden pass", "repair_improved")
    line("Runs where repair lowered hidden pass", "repair_hurt")
    if not audit_v2:
        rows = [[r[0], r[2]] for r in rows]
    out.append(captioned(table(rows, [7.6, 4.2, 4.7] if audit_v2 else [9, 7.5]),
                         "Table 13. Specification audit against the reference solutions."))
    return out


def section_results(story: list, units: tuple[int, int], refs: list, mut: dict, demo, bench: dict | None,
                    bench_v1: dict | None = None, bench_v2: dict | None = None, audit: dict | None = None,
                    audit_v2: dict | None = None) -> None:
    ms = mut["summary"]
    story += [P("10. Results", "h1"), P("10.1 Verification of the infrastructure", "h2"),
              P(f"The offline test suite (tests/test_core.py) passed {units[0]} of {units[0] + units[1]} tests. It "
                f"covers the safety gate, crash-frame capture, Hypothesis counterexamples, per-test timeouts, the "
                f"memory watchdog, post-mortem evaluation, probing, patch matching, loop detection, memory "
                f"retrieval and a complete scripted agent run. Every reference solution passed 100% of its hidden "
                f"tests ({sum(r[1] for r in refs)} test cases in total), which confirms that the hidden tests "
                f"measure what the prompts ask for.")]

    story += [P("10.2 Mutation study: what does each feedback channel reveal?", "h2"), P(C.MUTATION_METHOD),
              P(f"We generated {ms['mutants']} mutants and the hidden tests detected {ms['detected']} of them, a "
                f"mutation score of {pct(ms['mutation_score'])}. Figure 2 shows how the first failure of each "
                f"detected mutant appeared, and Figure 3 shows how often each diagnostic signal was available."),
              figure(FIG / "failure_categories.png", 11.5,
                     "Figure 2. How the first failure of each detected mutant appeared."),
              figure(FIG / "feedback_channels.png", 14.5,
                     "Figure 3. Availability of each diagnostic signal across detected mutants.")]
    rows = [["Task", "Mutants", "Detected"]] + [[k, str(v["mutants"]), str(v["detected"])]
                                                 for k, v in ms["per_task"].items()]
    story += [captioned(table(rows, [5, 3, 3]), "Table 7. Mutants per task (tasks with little arithmetic or "
                                                "comparison logic yield fewer mutation sites).")]

    # case study
    points, trial_starts, obs_n = [], [], 0
    for e in demo.events:
        if e["kind"] == "trial":
            trial_starts.append(obs_n + 1)
        if e["kind"] == "observation" and e["data"].get("total"):
            obs_n += 1
            label = "draft" if e["title"].startswith("Initial") else f"step {obs_n - len(trial_starts)}"
            points.append((label, e["data"]["passed"] / e["data"]["total"]))
    F.healing_curve(points, trial_starts, FIG / "healing_curve.png")
    patch_obs = next(e["data"]["text"] for e in demo.events
                     if e["kind"] == "observation" and "Edit applied" in e["data"].get("text", ""))
    prop_block = patch_obs[patch_obs.find("--- FAIL test_property"):]
    prop_block = "\n".join(prop_block.splitlines()[:8])
    evals = next(e["data"]["text"] for e in demo.events
                 if e["kind"] == "observation" and "Evaluated in" in e["data"].get("text", ""))
    reflection = next(e["data"]["text"] for e in demo.events if e["kind"] == "reflection")
    lesson = demo.lesson_learned or ""
    story += [P("10.3 Case study: one complete healing run", "h2"),
              P("To show the loop end to end without an API key, the repository ships a scripted demonstration. "
                "The model replies are pre-recorded, but everything else is real: the specification is validated, "
                "every test run, debugger evaluation and probe executes in the sandbox, and the reflection and "
                "lesson go through the memory module. The task is a running median, where the even-length case must "
                "average the two middle values."),
              P(f"The first draft always took the upper middle element and passed "
                f"{int(points[0][1] * 100)}% of the spec. Evidence-based triage kept the failing tests (they follow "
                f"from the task). The agent then used eval_at_crash to read the state of running_median() at the "
                f"moment it returned for the shrunk input:"),
              Preformatted(_wrap(evals, 92), S["code"]),
              P("It then patched the even-length branch, but kept floor division. The next observation shows the "
                "Hypothesis counterexample and the locals that exposed the remaining bug:"),
              Preformatted(_wrap(prop_block, 92), S["code"]),
              P("The step budget ran out after a probe, so the trial ended and the agent wrote this reflection:"),
              Preformatted(_wrap(reflection, 92), S["code"]),
              P(f"The second trial, conditioned on that reflection, passed every test on its first draft, and the "
                f"distilled lesson stored in long-term memory was: \"{esc(lesson)}\" Figure 4 shows the pass rate "
                f"after every observation. The run used {demo.usage['llm_calls']} model calls in "
                f"{demo.trials} trials."),
              figure(FIG / "healing_curve.png", 13.5,
                     "Figure 4. Specification pass rate across the scripted case study (real executions).")]

    story += [P("10.4 Pilot runs: what the live loop taught us", "h2"), P(C.PILOT_INTRO.format(n=len(C.PILOT_FINDINGS))),
              captioned(table([["Observed in the trace", "What happened and what we changed"]]
                              + [list(f) for f in C.PILOT_FINDINGS], [4.2, 12.3]),
                        "Table 8. Design changes made after the live pilot runs.")]

    story += [P("10.5 Live ablation on the benchmark", "h2")]
    if bench:
        summ = bench["summary"]
        F.strategy_bars(summ, "solve_rate", "tasks solved (%)", FIG / "solve_rate.png")
        F.strategy_bars(summ, "mean_hidden_pass_rate", "hidden tests passed (%)", FIG / "hidden_pass.png")
        rows = [["Arm", "Solved", "Hidden pass", "False conf.", "LLM calls", "Tokens", "Cost (USD)", "Time (s)"]]
        for s in summ:
            rows.append([s["label"], f"{s['solved']}/{s['tasks']}", pct(s["mean_hidden_pass_rate"]),
                         str(s["false_confidence"]), str(s["mean_llm_calls"]), str(s["mean_tokens"]),
                         f"{s['total_cost_usd']:.4f}", str(s["mean_wall_time_s"])])
        by = {s["strategy"]: s for s in summ}
        text = (f"All arms used model {bench['model']} with a budget of {bench['max_llm_calls']} LLM calls per task"
                + (f" and {bench['max_steps']} ReAct steps per Reflexion trial" if bench.get("max_steps") else "")
                + ". Each arm ran once on each task. ")
        if len(by) == 4:
            text += ("Table 9 summarises the four arms. One-shot generation solved "
                     f"{by['one_shot']['solved']} of {by['one_shot']['tasks']} tasks with a mean hidden pass rate of "
                     f"{pct(by['one_shot']['mean_hidden_pass_rate'])}. The traceback loop, rich feedback and the full "
                     f"agent solved {by['traceback_loop']['solved']}, {by['rich_feedback']['solved']} and "
                     f"{by['reflexdebug']['solved']} tasks, with mean hidden pass rates of "
                     f"{pct(by['traceback_loop']['mean_hidden_pass_rate'])}, "
                     f"{pct(by['rich_feedback']['mean_hidden_pass_rate'])} and "
                     f"{pct(by['reflexdebug']['mean_hidden_pass_rate'])}. The whole benchmark cost "
                     f"{sum(x['total_cost_usd'] for x in bench['summary']):.2f} USD. ")
        story += [P(text), captioned(table(rows, [3.3, 1.6, 1.9, 1.7, 1.7, 1.8, 2.0, 1.7]),
                                     "Table 9. Ablation results on hidden tests (means per task, cost summed)."),
                  figure(FIG / "solve_rate.png", 12, "Figure 5. Share of tasks fully solved, by arm."),
                  figure(FIG / "hidden_pass.png", 12, "Figure 6. Mean hidden test pass rate, by arm.")]
        matrix = [["Task"] + [s["label"] for s in summ]]
        for t in bench["tasks"]:
            row = [t]
            for s in summ:
                hit = next((r for r in bench["rows"] if r["task"] == t and r["strategy"] == s["strategy"]), None)
                if hit is None:
                    row.append("-")
                else:
                    row.append("SOLVED" if hit["hidden_solved"] else f"{hit['hidden_pass_rate']:.0%}")
            matrix.append(row)
        story += [captioned(table(matrix, [3.2] + [13.3 / len(summ)] * len(summ)),
                            "Table 10. Per-task result on hidden tests: SOLVED, or the share of hidden tests "
                            "passed.")]
        story += behaviour_section(bench)
        versions = [(lbl, data) for lbl, data in (("v1 (stopped)", bench_v1), ("v2", bench_v2), ("Final", bench))
                    if data]
        story += history_section(bench, versions)
        story += audit_section(audit, audit_v2)
    else:
        story += [P("The live ablation calls the OpenAI API for every arm and task, so it needs a key in .env. It is "
                    "fully automated: python cli.py bench runs the four arms on all 14 tasks, scores them on the "
                    "hidden tests and writes results/benchmark.json. Running python report/build_report.py again "
                    "then adds the results tables, the per-task matrix and the solve-rate and hidden-pass-rate "
                    "charts to this section. No live results are included in this copy of the report, and none "
                    "have been estimated or assumed.", "note")]


def live_values(bench, bench_v2, audit, audit_v2) -> dict:
    vals: dict = {}
    if bench:
        by = {x["strategy"]: x for x in bench["summary"]}
        for key, strat in (("one", "one_shot"), ("tb", "traceback_loop"), ("rich", "rich_feedback"),
                           ("rd", "reflexdebug")):
            if strat in by:
                vals[f"{key}_hidden"] = pct(by[strat]["mean_hidden_pass_rate"])
                vals[f"{key}_solved"] = f"{by[strat]['solved']}/{by[strat]['tasks']}"
        if "reflexdebug" in by:
            vals["final_calls"] = f"{by['reflexdebug']['mean_llm_calls']:.1f}"
            vals["final_cost"] = f"{by['reflexdebug']['total_cost_usd']:.3f}"
    if bench_v2:
        by2 = {x["strategy"]: x for x in bench_v2["summary"]}
        if "reflexdebug" in by2:
            vals["v2_calls"] = f"{by2['reflexdebug']['mean_llm_calls']:.1f}"
            vals["v2_cost"] = f"{by2['reflexdebug']['total_cost_usd']:.3f}"
    for tag, au in (("final", audit), ("v2", audit_v2)):
        if au:
            su = au["summary"]
            vals[f"{tag}_consistent"] = str(su["specs_consistent_with_reference"])
            vals[f"{tag}_improved"] = f"{su['repair_improved']} of {su['runs']}"
    if audit:
        vals["triage_total"] = str(audit["summary"].get("triage_amendments", 0))
        vals["triage_just"] = str(audit["summary"].get("triage_justified", 0))
    return vals


def section_end(story: list, mut: dict, bench=None, bench_v2=None, audit=None, audit_v2=None) -> None:
    ms = mut["summary"]
    vals = {"silent": pct(ms["silent_logic_bug_pct"]), "exact": pct(ms["crash_line_exact_pct_of_exceptions"]),
            "falsify": pct(ms["falsifying_example_pct_of_property_failures"]), "locals": pct(ms["locals_captured_pct"]),
            "assert_locals": pct(assertion_locals_rate(mut["records"]))}
    vals.update(live_values(bench, bench_v2, audit, audit_v2))
    story += [P("11. Discussion", "h1")]
    for head, text in C.DISCUSSION:
        try:
            body = text.format(**vals)
        except KeyError:  # a live-results paragraph without live results: leave it out rather than guess
            continue
        story += [P(head, "h2"), P(body)]
    story += [KeepTogether([P("12. Limitations", "h1"), bullets(C.LIMITATIONS[:2])]), bullets(C.LIMITATIONS[2:]),
              P("13. Conclusion", "h1"), P(C.CONCLUSION),
              P("14. Future work", "h1"), bullets(C.FUTURE), P("15. How to reproduce", "h1"),
              Preformatted("pip install -r requirements.txt\n"
                           "cp .env.example .env              # add OPENAI_API_KEY\n"
                           "pytest                             # offline test suite\n"
                           "python cli.py check                # hidden tests vs reference solutions\n"
                           "python -m benchmark.mutation_study # Section 10.2\n"
                           "python -m benchmark.safety_eval    # Section 8\n"
                           "python cli.py demo                 # Section 10.3, offline\n"
                           "python cli.py bench                # Section 10.5, needs a key\n"
                           "streamlit run app.py               # web interface\n"
                           "python report/build_report.py      # rebuild this PDF", S["code"]),
              P("References", "h1")]
    for i, ref in enumerate(C.REFERENCES, 1):
        story.append(P(f"[{i}] {esc(ref)}", "cell"))
        story.append(Spacer(1, 3))


def _wrap(text: str, width: int = 92) -> str:
    import textwrap

    lines = []
    for line in text.split("\n"):
        indent = len(line) - len(line.lstrip())
        lines.append(textwrap.fill(line, width, subsequent_indent=" " * (indent + 4)) if line.strip() else line)
    return "\n".join(lines)


def on_page(canvas, doc) -> None:
    if doc.page == 1:
        return
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(INK2)
    canvas.drawString(2 * cm, 1.2 * cm, "ReflexDebug: Debugger-Grounded Self-Healing Code Agent")
    canvas.drawRightString(A4[0] - 2 * cm, 1.2 * cm, f"Page {doc.page}")
    canvas.setStrokeColor(RULE)
    canvas.line(2 * cm, 1.55 * cm, A4[0] - 2 * cm, 1.55 * cm)
    canvas.restoreState()


def main() -> None:
    FIG.mkdir(exist_ok=True)
    for name, cmd in (("mutation_study", "python -m benchmark.mutation_study"),
                      ("safety_eval", "python -m benchmark.safety_eval")):
        if not (RESULTS / f"{name}.json").exists():
            sys.exit(f"results/{name}.json missing. Run: {cmd}")
    mut = json.loads((RESULTS / "mutation_study.json").read_text())
    safety = json.loads((RESULTS / "safety_eval.json").read_text())
    bench_path = RESULTS / "benchmark.json"
    bench = json.loads(bench_path.read_text()) if bench_path.exists() else None
    def load(name):
        path = RESULTS / name
        return json.loads(path.read_text()) if path.exists() else None

    bench_v1, bench_v2 = load("benchmark_v1.json"), load("benchmark_v2.json")
    audit, audit_v2 = load("spec_audit.json"), load("spec_audit_v2.json")

    print("running unit tests ...")
    units = run_unit_tests()
    print("checking reference solutions ...")
    refs = reference_check()
    print("running scripted case study ...")
    demo = run_demo()

    F.architecture(FIG / "architecture.png")
    F.failure_categories(mut["summary"], FIG / "failure_categories.png")
    F.feedback_channels(mut["summary"], FIG / "feedback_channels.png")

    doc = SimpleDocTemplate(str(OUT), pagesize=A4, leftMargin=2.2 * cm, rightMargin=2.2 * cm, topMargin=2 * cm,
                            bottomMargin=2.2 * cm, title=C.TITLE, author=", ".join(a[0] for a in C.AUTHORS),
                            subject=C.THEME)
    story: list = []
    cover(story)
    section_intro(story)
    section_design(story)
    section_safety(story, safety)
    section_setup(story)
    section_results(story, units, refs, mut, demo, bench, bench_v1, bench_v2, audit, audit_v2)
    section_end(story, mut, bench, bench_v2, audit, audit_v2)
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
